version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: login_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - php-auth-network

  php:
    build: .
    container_name: php-app
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST= postgres
    depends_on:
      - postgres
    networks:
      - php-auth-network

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - "8080:8080"
    networks:
      - php-auth-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  php-auth-network:
    driver: bridge
